name: Container

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build container
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          tags: mcp/dynatrace-managed-mcp-server:latest

  scan:
    runs-on: ubuntu-latest
    # Skip for PRs from forks since secrets are not available
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build container image for scanning
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          load: true
          tags: mcp/dynatrace-managed-mcp-server:scan

      - name: Run Snyk container scan
        uses: snyk/actions/docker@v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        with:
          image: mcp/dynatrace-managed-mcp-server:scan
          args: >
            --
            --severity-threshold=high
            --project-business-criticality=low
            --project-lifecycle=development
            --project-tags=team=team-se-cloud-automation
            --policy-path=.snyk
