name: SonarCloud
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Required by SonarCloud for blame information and new code detection

      - name: Use Node.js # will read version from .nvmrc
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:unit -- --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
